#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.Arm9{1,0,15.12,3
#
app.xe9: package/cfg/app.xe9.mak

clean::
	-$(RM) package/cfg/app.xe9.mak
