#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/utils.js:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/utils.js
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xdc.tci:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xdc.tci
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/template.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/template.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/om2.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/om2.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xmlgen.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xmlgen.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/xmlgen2.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/Warnings.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/Warnings.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/IPackage.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/IPackage.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/package.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/package.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/global/Clock.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/global/Trace.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/bld.js:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/bld.js
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/BuildEnvironment.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/PackageContents.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/_gen.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Library.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Library.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Executable.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Repository.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Configuration.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Script.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Script.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Manifest.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/Utils.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget2.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget3.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/ITargetFilter.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/package.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/bios_6_46_05_55/packages/ti/targets/ITarget.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/ITarget.xs
C:/ti/bios_6_46_05_55/packages/ti/targets/C28_large.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/C28_large.xs
C:/ti/bios_6_46_05_55/packages/ti/targets/C28_float.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/C28_float.xs
C:/ti/bios_6_46_05_55/packages/ti/targets/package.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/package.xs
C:/ti/bios_6_46_05_55/packages/ti/targets/arm/elf/IArm.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/arm/elf/IArm.xs
C:/ti/bios_6_46_05_55/packages/ti/targets/arm/elf/package.xs:
package.mak: C:/ti/bios_6_46_05_55/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/io/File.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/io/File.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/io/package.xs:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/services/io/package.xs
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/ccs620/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.Arm9.rootDir ?= C:/ti/ccs620/ccsv6/tools/compiler/arm_15.12.3.LTS
ti.targets.arm.elf.packageBase ?= C:/ti/bios_6_46_05_55/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe9
.PHONY: all,e9 .dlls,e9 .executables,e9 test,e9
all,e9: .executables,e9
.executables,e9: .libraries,e9
.executables,e9: .dlls,e9
.dlls,e9: .libraries,e9
.libraries,e9: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e9
	@$(ECHO) xdc .executables,e9
	@$(ECHO) xdc .libraries,e9
	@$(ECHO) xdc .dlls,e9


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,e9 .dlls: app.pe9

-include package/cfg/app_pe9.mak
-include package/cfg/app_pe9.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_pe9.dep
endif
app.pe9: package/cfg/app_pe9.xdl
	@


ifeq (,$(wildcard .libraries,e9))
app.pe9 package/cfg/app_pe9.c: .libraries,e9
endif

package/cfg/app_pe9.c package/cfg/app_pe9.h package/cfg/app_pe9.xdl: override _PROG_NAME := app.xe9
package/cfg/app_pe9.c: package/cfg/app_pe9.cfg
package/cfg/app_pe9.xdc.inc: package/cfg/app_pe9.xdl
package/cfg/app_pe9.xdl package/cfg/app_pe9.c: .interfaces

clean:: clean,e9
	-$(RM) package/cfg/app_pe9.cfg
	-$(RM) package/cfg/app_pe9.dep
	-$(RM) package/cfg/app_pe9.c
	-$(RM) package/cfg/app_pe9.xdc.inc

clean,e9::
	-$(RM) app.pe9
.executables,e9 .executables: app.xe9

app.xe9: |app.pe9

-include package/cfg/app.xe9.mak
app.xe9: package/cfg/app_pe9.oe9 
	$(RM) $@
	@$(MSG) lnke9 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.Arm9.rootDir)/bin/armcl -fs $(XDCCFGDIR)$(dir $@). -q -u _c_int00 --silicon_version=5e -z --strict_compatibility=on  -o $@ package/cfg/app_pe9.oe9   package/cfg/app_pe9.xdl  -w -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.arm.elf.Arm9.rootDir)/lib/libc.a
	
app.xe9: export C_DIR=
app.xe9: PATH:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/;$(PATH)
app.xe9: Path:=$(ti.targets.arm.elf.Arm9.rootDir)/bin/;$(PATH)

app.test test,e9 test: app.xe9.test

app.xe9.test:: app.xe9
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xe9.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xe9, ) 
endif

clean,e9::
	-$(RM) $(wildcard .tmp,app.xe9,*)


clean:: clean,e9

clean,e9::
	-$(RM) app.xe9
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_pe9.oe9,copy : package/cfg/app_pe9.oe9
app_pe9.se9,copy : package/cfg/app_pe9.se9

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
